# Simple render.yaml for Django application
services:
  - type: web
    name: blitzprompt
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "blitzprompt-q5x7.onrender.com,*.onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: "true"
    plan: free
    healthCheckPath: /health/

databases:
  - name: blitzprompt_db
    databaseName: blitzprompt
    user: blitzprompt
    ipAllowList: []  # Allow connections from anywhere
    plan: free
