services:
  - type: web
    name: blitzprompt
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn BlitzPrompt.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "blitzprompt.onrender.com,*.onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: PORT
        value: 10000
    plan: free
