services:
  - type: web
    name: blitzprompt
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "blitzprompt-q5x7.onrender.com,*.onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: blitzprompt_db
          property: connectionString
      - key: RENDER
        value: true
    plan: free
    healthCheckPath: /health/

databases:
  - name: blitzprompt_db
    databaseName: blitzprompt
    user: blitzprompt
    ipAllowList: []  # Allow connections from anywhere
    plan: free
