# Generated by Django 5.1.7 on 2025-03-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
