# Generated by Django 5.1.7 on 2025-03-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='is_priming',
            field=models.BooleanField(default=False, help_text="If True, this prompt will be used as a priming prompt before the user's query"),
        ),
        migrations.AddField(
            model_name='prompt',
            name='priming_order',
            field=models.IntegerField(default=0, help_text='Order in which priming prompts should be applied (lower numbers first)'),
        ),
    ]
